apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-service
  namespace: pdp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-service
  template:
    metadata:
      labels:
        app: kafka-service
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 39092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:39092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service.pdp.svc.cluster.local:39092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: pdp
spec:
  selector:
    app: kafka-service
  ports:
    - port: 39092
      targetPort: 39092