apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
  namespace: pdp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-service
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      containers:
        - name: weather-service
          image: weather-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
  namespace: pdp
spec:
  type: NodePort
  selector:
    app: weather-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
